minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - vite-plugin-deploy-ftp
  - vite-plugin-deploy-oss

ignoredBuiltDependencies:
  - '@tsparticles/engine'
  - cos-js-sdk-v5

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - sharp
  - vue-demi
