/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAudio: typeof import('./../src/components/base/audio.vue')['default']
    BaseBack: typeof import('./../src/components/base/back.vue')['default']
    BaseBackFace: typeof import('./../src/components/base/back-face.vue')['default']
    BaseBarrage: typeof import('./../src/components/base/barrage.vue')['default']
    BaseBarrageCard: typeof import('./../src/components/base/barrage-card.vue')['default']
    BaseBorderButton: typeof import('./../src/components/base/border-button.vue')['default']
    BaseButton: typeof import('./../src/components/base/button.vue')['default']
    BaseCaptcha: typeof import('./../src/components/base/captcha.vue')['default']
    BaseCode: typeof import('./../src/components/base/code.vue')['default']
    BaseCube: typeof import('./../src/components/base/cube.vue')['default']
    BaseImageScale: typeof import('./../src/components/base/image-scale.vue')['default']
    BaseKeyboard: typeof import('./../src/components/base/keyboard.vue')['default']
    BaseLike: typeof import('./../src/components/base/like.vue')['default']
    BaseLoading: typeof import('./../src/components/base/loading.vue')['default']
    BaseNumberFlow: typeof import('./../src/components/base/number-flow.vue')['default']
    BasePinchMove: typeof import('./../src/components/base/pinch-move.vue')['default']
    BaseScratchLottery: typeof import('./../src/components/base/scratch-lottery.vue')['default']
    BaseScroll: typeof import('./../src/components/base/scroll.vue')['default']
    BaseSealTouch: typeof import('./../src/components/base/seal-touch.vue')['default']
    BaseSearchSelect: typeof import('./../src/components/base/search-select.vue')['default']
    BaseSnow: typeof import('./../src/components/base/snow.vue')['default']
    BaseStars: typeof import('./../src/components/base/stars.vue')['default']
    BaseTransitionTop: typeof import('./../src/components/base/transition-top.vue')['default']
    BaseTypewriter: typeof import('./../src/components/base/typewriter.vue')['default']
    BaseWechatApplet: typeof import('./../src/components/base/wechat-applet.vue')['default']
    BaseWechatLogin: typeof import('./../src/components/base/wechat-login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
